"""add language to post

Revision ID: 24afc85a7f10
Revises: 2b29ac30bd78
Create Date: 2022-03-04 10:46:12.536081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24afc85a7f10'
down_revision = '2b29ac30bd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
